import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const hooksDir = path.join(process.cwd(), '.git', 'hooks');
const hookFile = path.join(hooksDir, 'commit-msg');

const hookContent = `#!/bin/sh
# commit-msg hook generated by commit-msg-lint
commit-msg-lint --file "$1"
`;

try {
  // Ensure .git/hooks directory exists
  if (!fs.existsSync(hooksDir)) {
    console.error('Error: .git directory not found. Are you in a git repository?');
    process.exit(1);
  }

  // Write hook file
  fs.writeFileSync(hookFile, hookContent);
  fs.chmodSync(hookFile, '0755');

  console.log('✅ Git hook installed successfully!');
  console.log('   commit-msg hook will now validate all commit messages');
} catch (error) {
  console.error('❌ Failed to install hook:', error);
  process.exit(1);
}
